all: clean build

build:
	cd 01_hello && make build
	cd 02_global && make build
	cd 03_sound && make build
	cd 04_heavy && make build
	cd 05_sprite256 && make build
	cd 06_save && make build
	cd 07_palette && make build
	cd 08_map-scroll && make build
	cd 09_joypad && make build
	cd 10_chr720 && make build
	cd 11_bigsprite && make build
	cd 12_angle && make build

clean:
	cd 01_hello && make clean
	cd 02_global && make clean
	cd 03_sound && make clean
	cd 04_heavy && make clean
	cd 05_sprite256 && make clean
	cd 06_save && make clean
	cd 07_palette && make clean
	cd 08_map-scroll && make clean
	cd 09_joypad && make clean
	cd 10_chr720 && make clean
	cd 11_bigsprite && make clean
	cd 12_angle && make clean
