all:
	cd 01_hello-asm && make clean build
	cd 02_global-asm && make clean build
	cd 03_sound-asm && make clean build
	cd 05_sprite256-asm && make clean build
	cd 06_save-asm && make clean build
	cd 07_palette-asm && make clean build
	cd 08_map-scroll-asm && make clean build
	cd 09_joypad-asm && make clean build
	cd 10_chr720-asm && make clean build
	cd 11_bigsprite-asm && make clean build
	cd 12_angle-asm && make clean build
	cd 13_perlin-asm && make clean build
	cd 14_1024ptn-asm && make clean build
	cd 15_nsf-asm && make clean build
	cd 16_ptn-plus1-asm && make clean build
	cd 17_clip-asm && make clean build

cpp-build:
	cd 01_hello && make build
	cd 02_global && make build
	cd 03_sound && make build
	cd 04_heavy && make build
	cd 05_sprite256 && make build
	cd 06_save && make build
	cd 07_palette && make build
	cd 08_map-scroll && make build
	cd 09_joypad && make build
	cd 10_chr720 && make build
	cd 11_bigsprite && make build
	cd 12_angle && make build
	cd 13_perlin && make build
	cd 14_1024ptn && make build
	cd 15_nsf && make build
	cd 16_ptn-plus1 && make build
	cd 17_clip && make build

cpp-clean:
	cd 01_hello && make clean
	cd 02_global && make clean
	cd 03_sound && make clean
	cd 04_heavy && make clean
	cd 05_sprite256 && make clean
	cd 06_save && make clean
	cd 07_palette && make clean
	cd 08_map-scroll && make clean
	cd 09_joypad && make clean
	cd 10_chr720 && make clean
	cd 11_bigsprite && make clean
	cd 12_angle && make clean
	cd 13_perlin && make clean
	cd 14_1024ptn && make clean
	cd 15_nsf && make clean
	cd 16_ptn-plus1 && make clean
	cd 17_clip && make clean
