CIRCLEHOME = ./circle
CHECK_DEPS = 0
STANDARD = -std=c++17
CFLAGS = -O3
CFLAGS += -I../../../src
CPPFLAGS = -O3
CPPFLAGS += -I../../../src
CPPFLAGS += -DZ80_DISABLE_DEBUG
CPPFLAGS += -DZ80_DISABLE_BREAKPOINT
CPPFLAGS += -DZ80_DISABLE_NESTCHECK
CPPFLAGS += -DZ80_CALLBACK_WITHOUT_CHECK
CPPFLAGS += -DZ80_CALLBACK_PER_INSTRUCTION
CPPFLAGS += -DZ80_UNSUPPORT_16BIT_PORT
CPPFLAGS += -DZ80_NO_FUNCTIONAL
CPPFLAGS += -DZ80_NO_EXCEPTION
CPPFLAGS += -D_TIME_T_DECLARED
OBJS = main.o
OBJS += std.o
OBJS += kernel.o
OBJS += splash.o
OBJS += lz4.o
OBJS += vgstone.o
LIBS = $(CIRCLEHOME)/lib/libcircle.a
LIBS += $(CIRCLEHOME)/lib/sound/libsound.a
LIBS += $(CIRCLEHOME)/lib/sched/libsched.a
LIBS += $(CIRCLEHOME)/addon/vc4/vchiq/libvchiq.a
LIBS += $(CIRCLEHOME)/addon/vc4/sound/libvchiqsound.a
LIBS += $(CIRCLEHOME)/addon/linux/liblinuxemu.a
LIBS += $(CIRCLEHOME)/addon/linux/liblinuxemu.a
LIBS += $(CIRCLEHOME)/lib/input/libinput.a
LIBS += $(CIRCLEHOME)/lib/fs/libfs.a
LIBS += $(CIRCLEHOME)/addon/fatfs/libfatfs.a
LIBS += $(CIRCLEHOME)/addon/SDCard/libsdcard.a
LIBS += $(CIRCLEHOME)/lib/usb/libusb.a
include $(CIRCLEHOME)/Rules.mk
-include $(DEPS)
